sudo: false
language: node_js
os:
- linux
node_js:
- lts/*
install:
- python --version
- pip install awscli --upgrade --user
- npm install gitbook-cli -g
script:
- gitbook build
- ls _book
- ./deploy.sh

cache:
  directories:
  - node_modules
env:
  global:
    - secure: bobeKggEdSwORQ0vpS8DT+85rgWxkcv9C6xkwp/YaenT0/dhl1juQGRzyf4iII4yaxK95ZmHp6EzvibwLvQby+EhIv6xrjr/MGbI4kiM/oiDWQxhr5gIL8pLxyHUdplgyP5lYFF6Ts1A1ng+rV7mRztsXcOqcNz7Foy2n/deyeSAq0/UzgP0QCz35rjg3vTs4urnx3oGXxQhTMbPJXe2bI3AilxoTShadt3/+hYPnQwLXeL+NbbRwIh5mcarkjPoOLApNXLqsd85o/vzOKihuKrLKrnQAHODm0WmCjWGJL9tbeBwTwDSvy9ar3Xt+qejGbfs5hiraW0Exnga94ppV2vOnyJ70LXQje3/FlYM98qyiiWvNLtCw+m00oQNoTn0U/l6jDgTdzkF1p8octerZ+JEHbCIWEfMtZ3ygm0yI4KmicsFICxDXchcow8LyUC70buKqXRwczNt0ppb2rTMW/bnQQsRX8d9qds24IZgDLEi+p1d2uAR1nEpC29PhVYiPwoPbp9sbt+ULdzDvVWh6g5M/VyA2IYfzsbPQsrdFFFVzp5YDBOHdxmHQTh97JBqZnqfCaZcBCzwOpEvtKA3yJUYzVPmRMlJj+m9jj/Qj0fyfgJGzj665Vv7Ez6ikFFnrW2CpGqSVJsiTQXnRmFzXFHKMEQGDaz2/+tWgKB9KKE=
    - secure: NVGG0LHR8Ja/sn2tmj0QvEKCrD9GTg7yvtW1al+tPvLKHqGUh+9PtDTjOK+hr/ivHmoyLHES0xfCfK+vw8KWIMwUmtAA7usdclIUzo194f2iI4+5Bzv/TGoUv2nNd+rgjMj5m/u/YP6FrW8m/ajWGS2Hwj29oXmqKaKi11xPgsl/Pxt/bQSsN2iY6m+1WKd+g1vOJ6lkjK4tBUXjkCqGQ1/tQCQwGeHO5gf2VY2x1AaD84HFafGLEFBJJFt/8njoXKc4wQKK1X1xCrcGHlaFLW0VojAKE/4JasBJxNq1hkoQwwQL7vU6VuCx4umj4twEQ5qKPYEhHYM5v9EZAOWBgM0GdIzHwRdThT7GfNU7vvIdTJ0eI5bf2NpWaDlbamqVDhBdSCeL1TfQr1P0RJtQysHHNv0vpmnC7zNIuyLCXnsWd2bmLs4WzMAIWs01OI3iBfkuZ+C4113VjPowmc37jTRYUvXySAYwYP00EsyKe3dMN0JjVGJsPIWv2UUWVmo+7+CzhIVY67f3BJhYTyKQZHiD0U1ZTjYtVb2iV3NKatLlKmAbzitLdRxi7RUpPObMHGB0I4ugBj5WqBW8VWV7dQIHXMIAcMJX3ISUCh9VlqWAEduBsB0+npRcjxcbuqTXUKH02OLn4VcV1a89/O9LOx/R/2Tfwqq5LSgLeMUermQ=
notifications:
  email:
    on_failure: always
